dist: focal
sudo: required
group: edge
arch: arm64-graviton2
virt: vm

service: docker

script:
- docker info 
- sudo apt-get install -y locate
- cat /usr/lib/systemd/system/docker.service
- sed -i '14s/.*/ExecStart=/usr/bin/dockerd -H fd:// --containerd=/run/containerd/containerd.sock --exec-opt native.cgroupdriver=systemd/' /usr/lib/systemd/system/docker.service
