dist: focal
sudo: required
group: edge
arch: arm64-graviton2
virt: vm

service: docker

script:
- docker build -t concourse_buildroot:curl-arm64 .
- docker login --username=mohneesh97979 --email=mohneesh9797@gmail.com
- docker push mohneesh9797/concourse_buildroot
